### ISSUE TITLE
Change embed order (Discord)

### ISSUE THREAD

**Issue by clr134** [robinuniverse/TwitFix#19]
Currently embeds are shown in reverse order, i.e. content is shown where username should be and username is shown where content should be.

**Comment by robinuniverse** [comment]
This is a restriction of using the oEmbed system that I am using, I am kinda forced to use the title field for the description because the description field only appears mobile clients because of a bug/oversight that I have reported in more detail here:
https://github.com/discord/discord-api-docs/discussions/3418

**Comment by clr134** [comment]
On both mobile and desktop both fields show up for me.

**Comment by robinuniverse** [comment]
Currently, twitfix only uses the Title (This is what is used to show the tweet description, and the position of this can't be changed) and Author( this is the blue author text, which also can't be changed ) fields. It might be possible to swap these, but the author field has a much more strict character limit, while the title field is only limited to 250 chars. the actual 'description' field is left unfilled because of the bug I mentioned, which can be seen here from early testing:

Mobile:
![img](https://user-images.githubusercontent.com/12601774/125000566-4c5d0900-e016-11eb-9779-a07facdc5dcf.png)

Desktop, same embed:
![img](https://user-images.githubusercontent.com/12601774/125000427-fd16d880-e015-11eb-8555-dc11ab3466a6.png)

**Comment by clr134** [comment]
Not sure what you actually use, what I meant is to just swap them, since both show up fine, and it's just weird to have the text above the author.

**Comment by robinuniverse** [comment]
The fields are in fixed locations and I don't have control over how discord places them, and I can't just swap them because the author field does not allow for nearly as much text as the title field, so I NEED to use the title field for the description
