### ISSUE TITLE
Request: Ability to raise quality of embeds

### ISSUE THREAD

**Issue by Silvea12** [robinuniverse/TwitFix#39]
Hey! At current, the system picks a low quality embed, rather than the full res video. While this works fine for some content, musical content becomes a problem, same with content with high motion.
For example, https://twitter.com/GooseworxMusic/status/1469147755880726530

On your embed, it fetches https://video.twimg.com/ext_tw_video/1469147214278627331/pu/vid/480x270/GrC7Vi18pGAaGJac.mp4
The highest quality is https://video.twimg.com/ext_tw_video/1469147214278627331/pu/vid/1280x720/PBAayR9c5-cIhTwF.mp4

The audio and video are both considerably clearer in these cases.
The chosen quality looks intentional, looking at the code - is there a reason for this? Higher quality embeds would be lovely to have.

If not by default, some other modification to the URL (path, query, etc) to enable this would be handy.

**Comment by Silvea12** [comment]
As a note, if the limitation here is simply engineering time, I can have a crack at it if it's not unwanted.

**Comment by robinuniverse** [comment]
Hi, sorry for the long delay on this as I've had a particularly busy week - The behavior is Half intentional, half sheer laziness, The way that it currently works is the simplest way to ensure that Most of the time the returned video was a .mp4 video, and only under really bad circumstances would it return something else. I've been meaning to make a better system for it, but I have had very little time for it. If you'd like to make a PR with a solution, I am in no way against that

**Comment by Silvea12** [comment]
No worries at all!

Do you have any info on the times other formats were returned? Specific types of tweets, formats to look out for, etc - I've never come across this so I don't know how to mitigate this without some more info.

**Comment by robinuniverse** [comment]
To give you that info I will have to set up a test environment which isn't really practical for me at the moment I'm afraid, I don't really have a solid machine to work on that isn't a laptop that I also use for work, so it may be some time before I can do tests to get the info needed. Though once I do, I can probably at least go ahead and fix the problem at that point, so that's good

**Comment by Silvea12** [comment]
If you know any of the characteristics I'm more than happy to look out for it myself, if it's inconvenient. I just don't have any samples on hand that I can use to test against for this weird behavior. Any common search queries/accounts/big posts that have the issue?

If you'd rather do it yourself, no stress, but I'm more than happy to take a look.

**Comment by Silvea12** [comment]
Any updates on this?
