### ISSUE TITLE
Feature request: Downloads

### ISSUE THREAD

**Issue by Sleepdealr** [robinuniverse/TwitFix#6]
Project is awesome btw, super useful.

Would love to see a download button for the media of the tweet.
The text here could be used as an easy download link instead of going through something like youtube-dl manually.
![image](https://user-images.githubusercontent.com/35879391/125456433-734bc10a-100e-4ee3-acdc-053bcc5cb4fb.png)

**Comment by robinuniverse** [comment]
It's an interesting idea but I think I need to put this on the backburner
I've done a LOT of poking and prodding with the embed and the amount of content I have in it now is basically the max I can figure out how to get into it without breaking the video playback, and even this much was a huge pain because I had to create a whole oEmbed enpoint system just to be able to handle it. I'm very open to being proven wrong with PRs, though
